### PR TITLE
Filtering + token auth

### PR DESCRIPTION
**Pull request by jasny**
* Added option to connect with GitHub token instead of u/p
* Pass credentials instead of username / password when using as module
* Added option to connect to Travic-CI pro (= travis-ci.com)
* Filter on branch by name
* Filter on event type (push or pull-request)
* Upgrade to travis-ci package v2.x (from v1.x)
* Show build number in output when successfull
* Show proper error when no builds are found

### CODE REVIEW

**Comment by jasny** [comment]
Sorry for sending such a massive PR instead of small ones.

**Comment by patrickkettner** [comment]
awesome work!
Would you be able to add a GITHUB_TOKEN env var check in case someone doesn't want to use a flag?

cheers!

**Comment by patrickkettner** [comment]
why the close?

**Comment by jasny** [comment]
Sorry deleted the branch accidentally. :frowning: It's back...

**Comment by patrickkettner** [comment]
:]

**Comment by jasny** [comment]
I've added support for both `GITHUB_TOKEN` and `GH_TOKEN`. (I use `GH_TOKEN` myself.)

The order is `--token`, `GITHUB_TOKEN`, `GH_TOKEN`, tty.

**Comment by patrickkettner** [comment]
thanks a bunch! published as 1.0.0

**Comment by jasny** [comment]
Thanks, your the best! :smile:

**Pull request merged**
